In [1]:
import numpy as np

In [119]:
A = np.loadtxt("A.txt", delimiter=' ', dtype=np.float)
B = np.loadtxt("B.txt", delimiter=' ', dtype=np.float)
epsilon = 10 **(-5)
U,L = np.zeros(A.shape), np.zeros(A.shape)
print("Matrix A")
print(A)

Matrix A
[[  6.81    0.88    1.19    1.165  -0.51 ]
 [  1.32    3.61    1.3    -1.63   -1.98 ]
 [  0.75   -2.46    5.99    2.1    -1.517]
 [  1.315   0.16    2.1     5.55   22.   ]
 [  0.99    1.32    1.783 -11.     16.   ]]


In [126]:
def LU(A):
    if np.max(np.abs(A)==0):
        print("System don't have roots")
        return None
    for j in range(0,A.shape[1]):
        U[0][j] = A[0][j]
        L[j][0] = A[j][0] / U[0][0]
    for i in range(0,A.shape[0]):
        for j in range(i,A.shape[1]):
            sumL,sumU = 0,0
            for k in range(0,i):
                sumU += L[i][k]*U[k][j]
                sumL += L[j][k]*U[k][i]
            U[i][j] = A[i][j] - sumU
            L[j][i] = (1/U[i][i]) * (A[j][i] - sumL)
    return L,U

In [127]:
L,U = LU(A)
print("Matrix L")
print(L)
print("Matrix U")
print(U)

Matrix L
[[ 1.          0.          0.          0.          0.        ]
 [ 0.1938326   1.          0.          0.          0.        ]
 [ 0.11013216 -0.74341338  1.          0.          0.        ]
 [ 0.19309838 -0.00288611  0.28153385  1.          0.        ]
 [ 0.14537445  0.34658982  0.18626394 -2.06412461  1.        ]]
Matrix U
[[ 6.81        0.88        1.19        1.165      -0.51      ]
 [ 0.          3.43942731  1.06933921 -1.85581498 -1.88114537]
 [ 0.          0.          6.65390381  0.59205834 -2.85930125]
 [ 0.          0.          0.          5.15299982 22.89804107]
 [ 0.          0.          0.          0.         64.5231217 ]]


In [116]:
def revers_matrix(L,U):
    alpha = np.zeros(L.shape)
    beta = np.zeros(U.shape)
    for i in range(0,alpha.shape[0]):
        alpha[i][i] = 1 / U[i][i]
        beta[i][i] = 1 / L[i][i]
    for i in range(0,L.shape[0]):
        for j in range(0,L.shape[1]):
            if i > j:
                alpha[i][j] = 0
                sumL = 0
                for k in range(0,i):
                    sumL += beta[k][j] * L[i][k]
                beta[i][j] = (-1/L[i][i])*sumL
            elif i < j:
                beta[i][j] = 0
                sumU = 0
                for k in range(0,j):
                    sumU += alpha[i][k] * U[k][j]
                alpha[i][j] = (-1/U[j][j]) * sumU
    return beta,alpha

In [117]:
L_reverse,U_reverse = revers_matrix(L,U)
print("Reverse matrix L")
print(L_reverse)
print("Reverse matrix U")
print(U_reverse)

Reverse matrix L
[[ 1.          0.          0.          0.          0.        ]
 [-0.1938326   1.          0.          0.          0.        ]
 [-0.25422991  0.74341338  1.          0.          0.        ]
 [-0.12208348 -0.20640992 -0.28153385  1.          0.        ]
 [-0.2828357  -0.91111672 -0.76738489  2.06412461  1.        ]]
Reverse matrix U
[[ 0.14684288 -0.03757071 -0.0202238  -0.0444057   0.01492785]
 [ 0.          0.29074608 -0.04672538  0.11007861 -0.03265885]
 [ 0.          0.          0.15028772 -0.01726744  0.01278779]
 [ 0.          0.          0.          0.19406172 -0.06886885]
 [ 0.          0.          0.          0.          0.01549832]]


In [120]:
X = np.dot(np.dot(U_reverse,L_reverse),B)

In [121]:
r = np.abs(B-np.dot(A,X)) < epsilon

In [125]:
print("Our mismatch vector")
print(r)

Our mismatch vector
[ True  True  True  True  True]


In [136]:
print("Reverse A matrix")
print(np.dot(U_reverse,L_reverse))

Reverse A matrix
[[ 0.16046587 -0.05704059 -0.01917749 -0.01359276  0.01492785]
 [-0.04867877  0.26304451 -0.05265433  0.04266668 -0.03265885]
 [-0.03971641  0.1036389   0.14533592  0.00912816  0.01278779]
 [-0.00421316  0.0226913  -0.00178603  0.05190783 -0.06886885]
 [-0.00438348 -0.01412078 -0.01189318  0.03199046  0.01549832]]


In [134]:
X  

array([ 0.45729966,  0.09363033, -0.76863834, -0.22166453, -0.14963415])

In [135]:
np.linalg.solve(A,B)

array([ 0.45729966,  0.09363033, -0.76863834, -0.22166453, -0.14963415])

In [146]:
detA = 1
for i in X:
    detA *= i
print("Determinate A equals")
print(detA)


Determinate A equals
-0.0010916071900617223
