In [110]:
import numpy as np


In [111]:
A = np.loadtxt("A.txt", delimiter=' ', dtype=np.float)
epsilon = 10 **(-5)
U,L = np.zeros(A.shape), np.zeros(A.shape)
print("Matrix A")
print(A)

Matrix A
[[6.81  0.88  1.19  1.165]
 [0.88  3.61  1.3   0.16 ]
 [1.19  1.3   5.99  2.1  ]
 [1.165 0.16  2.1   5.55 ]]


In [113]:
def qr(A):
    m, n = A.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        H = np.eye(m)
        H[i:, i:] = make_householder(A[i:, i])
        Q = np.dot(Q, H)
        A = np.dot(H, A)
    return Q, A
 
def make_householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H



In [188]:
Q,R = qr(A)
print("Matrix q")
print(Q)
print("Matrix r")
print(R)

Matrix q
[[-0.9638139   0.1675163   0.1719312  -0.1159341 ]
 [-0.1245457  -0.94283319  0.290915    0.10451035]
 [-0.16841976 -0.28692393 -0.88471677 -0.32647464]
 [-0.16488153  0.02604863 -0.32106755  0.93222915]]
Matrix r
[[-7.06567937e+00 -1.54309295e+00 -2.66393350e+00 -2.41154447e+00]
 [ 1.11081560e-16 -3.62504678e+00 -2.69031094e+00 -4.13667142e-01]
 [-1.54842977e-17  2.05980778e-16 -5.39090766e+00 -3.39298386e+00]
 [-6.92832623e-18  8.35177784e-17  2.22044605e-16  4.36993344e+00]]


In [190]:
A_next = A
iteration = 1
vekt = 0
while(True):
    A_prev = A_next
    q,r = qr(A_prev)
    print("\nIteration:", iteration)
    print("\nMatrix Q\n")
    print(q)
    print('\nMatrix R\n')
    print(r)
    A_next = np.dot(r,q)
    if iteration == 1:
        vekt = q
    else:
        vekt = np.dot(vekt,q)
    err = np.abs(np.diag(A_prev)-np.diag(A_next))
    print("\nCriterion of convergence: {}\n".format(err))
    print("\nFrobenious norm: {}\n".format(np.linalg.norm(A_next)))
    
    iteration += 1
    
    x = np.array(np.dot(A,vekt) - np.diag(A_next)*vekt)
    
    print("Vector of disconnection:\n",x)
 
    if(np.all(x< 0.00001)):
        break;
vekt = np.dot(vekt,q)


Iteration: 1

Matrix Q

[[-0.9638139   0.1675163   0.1719312  -0.1159341 ]
 [-0.1245457  -0.94283319  0.290915    0.10451035]
 [-0.16841976 -0.28692393 -0.88471677 -0.32647464]
 [-0.16488153  0.02604863 -0.32106755  0.93222915]]

Matrix R

[[-7.06567937e+00 -1.54309295e+00 -2.66393350e+00 -2.41154447e+00]
 [ 1.11081560e-16 -3.62504678e+00 -2.69031094e+00 -4.13667142e-01]
 [-1.54842977e-17  2.05980778e-16 -5.39090766e+00 -3.39298386e+00]
 [-6.92832623e-18  8.35177784e-17  2.22044605e-16  4.36993344e+00]]

Criterion of convergence: [1.03846376 0.56895352 0.1311966  1.47622068]


Frobenious norm: 12.059745022180195

Vector of disconnection:
 [[ 0.4987791  -0.70004284 -1.00731108  0.47228995]
 [-0.56560051  0.31500928 -1.70441379 -0.42575212]
 [-1.34209715 -1.49126918 -0.20752606  1.32998563]
 [-1.11747778 -0.52252318 -1.51191222  0.57223763]]

Iteration: 2

Matrix Q

[[-0.97186084  0.16256528  0.160467    0.05752713]
 [-0.12045899 -0.94592766  0.27375798 -0.12556693]
 [-0.18170244 -0.273

In [191]:
print("Eigenvalues: ",np.diag(A_next))
print("\nEigenvectors:\n\n",vekt)


Eigenvalues:  [9.42717549 5.60080878 4.23096936 2.70104636]

Eigenvectors:

 [[-0.57590691  0.80168049 -0.09720175 -0.12724558]
 [-0.23456326  0.02559006  0.59244172  0.77028438]
 [-0.59745051 -0.45602396  0.43164873 -0.4987729 ]
 [-0.50632419 -0.3856108  -0.67323398  0.37642546]]
